### ISSUE TITLE
Unparseable value for ttl field

### ISSUE THREAD

**Issue by jmerriweather** [KindyNowApp/ex_nexmo#9]
When attempting to send an sms I get {:error, :invalid_ttl} and error_test: Unparseable value for ttl field

**Comment by jmerriweather** [comment]
I've fixed this issue here: https://github.com/jmerriweather/ex_nexmo/tree/fix-ttl-invalid i based this on the 1.4 branch so i'll send a pull request once that's been merged

**Comment by craigp** [comment]
@jmerriweather catching up on this, apologies we let it go for so long - would be happy to receive any and all PRs

**Comment by craigp** [comment]
@jmerriweather is it possible to create a pull request for your fixes? Otherwise I'll likely close this issue soon.

**Comment by jmerriweather** [comment]
this can be closed as the latest master has fixed the issue of sending a ttl of nil
